---
title: "Reproducible documents"
author: "Pauline Reim"
format: html
---

1. Pauline Reim
2. NNF CBMR, University of Copenhagen

# Intro

This **is** a random *sentence*

# Methods and Results

I **don't** know what to *write*

## Analyses

**This is fun**

# Discussion

Have a *nice* **day** 

```{r setup}
#| message: false
#| warning: false
library(tidyverse)
library(NHANES)
NHANES_snakecase <- read_csv(here::here("data/NHANES_snakecase.csv"))
```

```{r}
NHANES_snakecase <- NHANES_snakecase %>%
  select(age, sex, bmi, diabetes, phys_active, bp_sys_ave, bp_dia_ave, education)
NHANES_snakecase
```

# Table of results

```{r}
NHANES_snakecase %>%
  filter(!is.na(diabetes)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  knitr::kable(caption = "Mean values of age and BMI")
```

## Prettier table

```{r}
#| echo: false
#| warning: false
NHANES_snakecase %>%
  filter(!is.na(diabetes), !is.na(education)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    # Task 2a.
    mean_age = round(mean_age, digits = 1),
    mean_bmi = round(mean_bmi, digits = 1),
    # Task 2b.
    education = str_to_sentence(education)
  ) %>% 
  rename(
    # Task 3.
    "Mean Age" = mean_age,
    "Mean BMI" = mean_bmi,
    "Education" = education,
    "Diabetes Status" = diabetes
  ) %>% 
  knitr::kable(caption = "Mean values of Age and BMI")
```

